[package]
name = "AdventOfCode2020"
version = "0.1.0"
authors = ["scturtle <scturtle@gmail.com>"]
edition = "2018"

[dependencies]
ureq = "2.0.0-rc2"
itertools = "0.9"
dotenv = "0.15"
regex = "1.4"
rand = "0.7"
